//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPOOLING_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid BookingID { get; set; }
        public System.Guid RideID { get; set; }
        public System.Guid PassengerID { get; set; }
        public Nullable<System.Guid> PickupStopID { get; set; }
        public Nullable<System.Guid> DropStopID { get; set; }
        public int SeatsRequested { get; set; }
        public decimal Fare { get; set; }
        public byte StatusID { get; set; }
        public Nullable<bool> PaymentConfirmed { get; set; }
        public Nullable<System.DateTime> RequestedAt { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Stop Stop1 { get; set; }
        public virtual Ride Ride { get; set; }
        public virtual BookingStatu BookingStatu { get; set; }
    }
}
