//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPOOLING_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public System.Guid RatingID { get; set; }
        public System.Guid RideID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<System.Guid> PassengerID { get; set; }
        public byte Stars { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Ride Ride { get; set; }
    }
}
