//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARPOOLING_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ride()
        {
            this.Bookings = new HashSet<Booking>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public System.Guid RideID { get; set; }
        public System.Guid DriverID { get; set; }
        public Nullable<System.Guid> VehicleID { get; set; }
        public System.Guid RouteID { get; set; }
        public int TotalSeats { get; set; }
        public int AvailableSeats { get; set; }
        public System.DateTime StartTime { get; set; }
        public decimal PricePerSeat { get; set; }
        public byte StatusID { get; set; }
        public Nullable<System.DateTime> PostedAt { get; set; }
        public Nullable<System.DateTime> ExpiryAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Route Route { get; set; }
        public virtual RideStatu RideStatu { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
